name: 'Mark old flaky tests issues as stale'
on:
    schedule:
        - cron: '20 1 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7.0.0
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: 'This issue has gone 30 days without any activity.'
                  days-before-stale: 30
                  days-before-close: 1
                  only-labels: '[Type] Flaky Test'
                  stale-issue-label: '[Status] Stale'
